[default]
timeout = 30

[alzenau_news]
title = "Alzenau - Mitteilungen"
url = "https://www.alzenau.de/B%C3%BCrger/Rathaus-Service/Ver%C3%B6ffentlichungen/Pressemeldungen-Aktuelles/"
entrySelector = ".mitteilungen"
titleSelector = "a[title]"
linkSelector = "a[title]"
contentSelector = [".liste_bild", ".liste_text"]
